[project]
name = 'clarity-stacking-pools'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3C0TCQS0C0YY8E0V3EJ7V4X9571885D44M8EFWF.arkadiko-automation-trait-v1'

[[project.requirements]]
contract_id = 'SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox-fast-pool-v2'

[contracts.pox4-self-service-v3]
path = 'contracts/pox4-self-service.clar'
clarity_version = 2
epoch = 2.5

[contracts.pox4-self-service-multi]
path = 'contracts/pox4-self-service-multi.clar'
clarity_version = 2
epoch = 2.5

[contracts.pox4-pools]
path = 'contracts/pox4-pools.clar'
clarity_version = 2
epoch = 2.5

[contracts.helper]
path = 'contracts/testing/helper.clar'
clarity_version = 2
epoch = 2.5

### Additional contracts
[contracts.payout-self-service]
path = 'contracts/payout/payout-self-service.clar'
clarity_version = 2
epoch = 2.5

[contracts.payout-trait]
path = 'contracts/payout/payout-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.payout-90-10-project]
path = 'contracts/payout/payout-90-10-project.clar'
clarity_version = 2
epoch = 2.5

[contracts.fp-auto-extend]
path = 'contracts/fast-pool/fp-auto-extend.clar'
clarity_version = 2
epoch = 2.5

###
### Tests
###

[contracts.pox4-pools_flow_test]
path = 'tests/pox4-pools_flow_test.clar'
clarity_version = 2
epoch = 2.5
