name: CI
on: [push]
jobs:
  tests:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Check contracts"
        uses: docker://hirosystems/clarinet:2.5.1
        with:
          args: check --manifest-path=./Clarinet.toml
      - name: "Run unit tests"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: yarn install
      - run: yarn test
      - name: "Export code coverage"
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.lcov
          verbose: true
